version: '2'
services:
  atty-app:
    image: atty
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://atty-postgresql:5432/atty
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8077:8077
  atty-postgresql:
    extends:
      file: postgresql.yml
      service: atty-postgresql
