version: '2'
services:
  atty-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/atty/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=atty
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
